#cloud-config
packages:
  - apache2
write_files:
 - content: |
    <html>
     <body>
      <h1>CNT Gruppenarbeit Reverse Proxy</h1>
       <ul>
       <li><a href="/Webseite1">Webseite1</a></li>
       <li><a href="/Webseite2">Webseite2</a></li>
       </ul>
     </body>
    </html>
   path: /var/www/html/index.html
   permissions: '0644'  
 - content: |
    ProxyRequests Off
    <Proxy *>
          Order deny,allow
          Allow from all
    </Proxy>
    ProxyPass /Webseite1 http://Webseite1         
    ProxyPassReverse /Webseite1 http://Webseite1 
    ProxyPass /Webseite2 http://Webseite2         
    ProxyPassReverse /Webseite2 http://Webseite2  
   path: /etc/apache2/sites-enabled/001-reverseproxy.conf
   permissions: '0644'  
runcmd:
 - sudo a2enmod proxy
 - sudo a2enmod proxy_html
 - sudo a2enmod proxy_http
 - sudo service apache2 restart 
